apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng2
  namespace: argocd
spec:
  project: default
  source:
    path: charts/myapp
    repoURL: https://github.com/chemical081/kube.git
    targetRevision: master
    helm:
      releaseName: ng2

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ng2

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
