apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng2
  namespace: argocd
spec:
  project: default
  source:
    path: charts/myapp
    repoURL: https://github.com/chemical081/kube.git
    targetRevision: master
    helm:
      releaseName: ng2
      values: |
        replicaCount: 5
        fullnameOverride: "ng2"
        image: 
          repository: razzkumar/static
          tag: "latest"
        service:
          port: 3000
        ingress:
          enabled: true
          className: "traefik"
          annotations: {}
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: ng2.local.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
          #  - secretName: chart-example-tls
          #    hosts:
          #      - chart-example.local  
                

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ng2

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
